AllCops:
  TargetRubyVersion: 3.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
