repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
# Optional mypy hook - may need 'files: ^src/' if uncommented
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.10.0'
#     hooks:
#     -   id: mypy
